
service: fwc2018

custom:
  defaultStage: dev
  vars: ${file(./config/env.yml)}
  line: ${file(./config/events/line.yml)}
  updateMatches: ${file(./config/events/update-matches.yml)}
  updateGroupResults: ${file(./config/events/update-group-results.yml)}
  defaultRole: ${file(./config/defaultRole.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  profile: relifeted
  region: us-west-2
  role: defaultRole
  deploymentBucket: relifeted.info-deployments-us-west-2

package:
  excludeDevDependencies: false

functions:
  line:
    handler: build/main.line
    memorySize: 1536
    timeout: 30
    environment:
    events: ${self:custom.line}
  updateMatches:
    handler: build/main.updateMatches
    memorySize: 1536
    timeout: 30
    environment:
    events: ${self:custom.updateMatches}
  updateGroupResults:
    handler: build/main.updateGroupResults
    memorySize: 1536
    timeout: 30
    environment:
    events: ${self:custom.updateGroupResults}


resources:
  Resources:
    defaultRole: ${self:custom.defaultRole}