query($type: String!) {
  findMatchByType(type: $type) {
    id
    name
    type
    homeTeamId
    awayTeamId
    group
    homeTeam {
      id
      name
      fifaCode
      iso2
      flag
      emoji
      emojiString
    }
    awayTeam {
      id
      name
      fifaCode
      iso2
      flag
      emoji
      emojiString
    }
    homeResult
    awayResult
    homePenalty
    awayPenalty
    dateTime
    matchDate
    timestamp
    finished
    matchday
  }
}
