query($matchDate: String!) {
  findMatchByDate(matchDate: $matchDate) {
    id
    name
    type
    homeTeamId
    awayTeamId
    group
    homeTeam {
      id
      name
      fifaCode
      iso2
      flag
      emoji
      emojiString
      group
    }
    awayTeam {
      id
      name
      fifaCode
      iso2
      flag
      emoji
      emojiString
      group
    }
    homeResult
    awayResult
    dateTime
    matchDate
    stadiumId
    stadium {
      id
      name
      city
      lat
      lng
      image
    }
    finished
    matchday
  }
}
